### ISSUE TITLE
Tutorial - Feedback

### ISSUE THREAD

**Issue by Ithien** [infinispan/infinispan-server-tutorial#2]
Hi,

My (setup/work configuration)  is a Windows10, Docker and  IntelliJ IDE.

I've needed a 35 mintes to do the tutorial

I had two problems, which are easily to fix

- The first problem happens in the execution of AppClass "TemperatureLoaderApp"  doesn't compile due to a missing dependency "infinitispan-query-dsl". Once added, the problem has been solved

- Next issue appears in  "getForLocation"  method, which uses a method "fetchTemperature" with an overload "String location" but the sources don't have this signature. I had modify it to use the method without that overload parameter.

**Comment by karesti** [comment]
@Ithien thank you!!! I will fix those

**Comment by karesti** [comment]
I reported the changes, thank you!
